@startuml

title Информационная  система технической экспертизы
skinparam backgroundcolor AntiqueWhite/Gold
participant соискатель
participant эксперт
participant держатель
participant заявка
participant решение

activate соискатель
activate заявка
соискатель -> заявка: подаёт заявку
deactivate заявка
activate решение
соискатель -> решение: ждёт решение
deactivate решение
deactivate соискатель
activate эксперт
activate заявка
эксперт -> заявка: оценивает заявку
deactivate заявка
activate держатель
эксперт -> держатель: уведомляет
deactivate эксперт
activate заявка
держатель -> заявка: смотрит на оценку эксперта
заявка -> держатель: получает оценку заявки
deactivate заявка
activate решение
держатель -> решение: выносит решение
deactivate держатель
activate соискатель
решение -> соискатель: решение принято
deactivate решение
deactivate соискатель

@enduml